[project]
name = "funfrp"
version = "0.1.1"
description = "funfrp"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[tool.setuptools]
license-files = []
